### ISSUE TITLE
essentialcarefulbreak and other features arent working?

### ISSUE THREAD

**Issue by SouthernPixel** [Super-Santa/EssentialAddons#54] opened 2022-08-26 04:54 UTC
idk why but careful break and /cam isn't working. it says /cam isn't even a command even though it worked fine before and with careful break it says its on but when i crouch and break a block with my pickaxe and a empty space in my inventory it doesn't go straight into my inventory

**Comment by senseiwells** [comment] 2022-08-29 18:08
`/cam` is not a command that is part of EssentialAddons, the rest is a duplicate of #52

**Closed by senseiwells** 2022-08-29 18:08 UTC
