### ISSUE TITLE
Messes with redstone components.

### ISSUE THREAD

**Issue by Missunderstood80** [Super-Santa/EssentialAddons#76] opened 2024-02-08 09:24 UTC
Hi there. I had a Tunnel Bore already setup, came across this mod and since I loved Essentials and EssentialsX from Paper/Spigot, I thought I would install this. After installing this on my server and without subscribing to any of the settings my tunnel bore blew itself up.

At first I didn't even think that this mod was the issue so I built the tunnel bore again and low and behold it blew up again. As a precaution I removed the mod as it was the last thing I had changed server side when the tunnel bore was working. After re-building the machine again it worked absolutely fine, so something in the mod is messing with something redstone related.

I'm sorry that I can't give any better details, only that I built this as an exact copy of Docm77's Tunnel Bore from Hermitcraft Season 9 and I took a litematica of it for my own world, but either way, the machine was fine before the mod. I hope you figure out what it is and maybe it can save someone else a headache.

**Comment by senseiwells** [comment] 2024-02-12 23:12
I cannot reproduce this issue, using [this tunnel bore world download](https://www.youtube.com/watch?v=oWUpTIirzJQ), which is the one docm uses. Can you please provide more information:
- Ensure that the tunnel bore does indeed break with EA. e.i. take a backup of your world and run it both with and without EA. (it may be possible that you simply built in wrong, as I cannot reproduce with the world download).
- If you are certain that it does break please upload a copy of your world so I can reproduce the bug.

**Comment by senseiwells** [comment] 2024-03-13 22:32
Closing this as it's been a month, and I have no received any similar issues and I cannot reproduce.

**Closed as completed by senseiwells** 2024-03-13 22:32 UTC
